// Admin Pages Index
export { AdminLogin } from './AdminLogin';
export { AdminDashboard } from './AdminDashboard';
export { StudentsManagement } from './StudentsManagement';
export { SchoolsManagement } from './SchoolsManagement';
export { ClassesManagement } from './ClassesManagement';
export { SubjectsManagement } from './SubjectsManagement';
export { SubjectMapping } from './SubjectMapping';
export { PlansManagement } from './PlansManagement';
export { TransactionsManagement } from './TransactionsManagement';
export { Analytics } from './Analytics';
export { Reports } from './Reports';
export { AdminUsersManagement } from './AdminUsersManagement';
export { AdminSettings } from './AdminSettings';
export { AdminProfile } from './AdminProfile';
export { BoardsManagement } from './BoardsManagement';
export { BoardAdd } from './BoardAdd';
export { BoardEdit } from './BoardEdit';
export { BoardView } from './BoardView';
